exclude: "external/gcsfs/"
repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
      additional_dependencies: ["click==8.0.4"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: trailing-whitespace
    - id: flake8
      name: flake8
      language_version: python3
      args: [--config, setup.cfg]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    - id: mypy
      args: [
          --follow-imports, silent
        ]
